# Generated by Django 5.2.3 on 2025-06-24 16:39

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file_directory', models.TextField()),
                ('source', models.TextField()),
                ('last_modified', models.DateTimeField()),
                ('filetype', models.TextField()),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_historys',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('element_id', models.TextField(blank=True, null=True)),
                ('page_content', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='polls.document')),
            ],
            options={
                'db_table': 'chunks',
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_data', pgvector.django.vector.VectorField(dimensions=1024)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='polls.chunk')),
            ],
            options={
                'db_table': 'embeddings',
            },
        ),
        migrations.CreateModel(
            name='EmphasizedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tag', models.TextField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emphasized_texts', to='polls.chunk')),
            ],
            options={
                'db_table': 'emphasized_text',
            },
        ),
    ]
